[tool.poetry]
name = "TryGitHubApi"
version = "0.1.0"
description = ""
authors = ["Haruhiko Takada <haruhiko.takada@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
PyGithub = "^1.45"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
main = "trygithubapi.main:main"
